### ISSUE TITLE
Error with relative path

### ISSUE THREAD

**Issue by creadone** [brookemckim/hlspider#3]
Some playlists may include relative path to chunklist.

See example:

Url to main playlist:
```
http://domain.com/live/_definst_/smil:russkiyroman_sd/playlist.m3u8
```

Сontents of playlist:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=500000
/russkiyroman/270p/live.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=2,BANDWIDTH=900000
/russkiyroman/360p/live.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=3,BANDWIDTH=1500000
/russkiyroman/406p/live.m3u8
```
By default HLSpider convert this urls to:
```
http://domain.com/live/_definst_/smil:russkiyroman_sd//russkiyroman/270p/live.m3u8
http://domain.com/live/_definst_/smil:russkiyroman_sd//russkiyroman/360p/live.m3u8
http://domain.com/live/_definst_/smil:russkiyroman_sd//russkiyroman/406p/live.m3u8
```
I think it is a mistake. In the right case HLSpider it should do convert to urls from root:

```
http://domain.com/russkiyroman/270p/live.m3u8
http://domain.com/russkiyroman/360p/live.m3u8
http://domain.com/russkiyroman/406p/live.m3u8
```

**Comment by shafqatevo** [comment]
Hi there, has this been merged to the code? We also need to use relative URLs.

**Comment by bkosborne** [comment]
Not sure if @wandenberg is still around here or not, but I've merged his branch into master now. I haven't looked at this code in a while so I'll revisit later and bump the version release.

**Comment by shafqatevo** [comment]
Thanks, @bkosborne!

**Comment by wandenberg** [comment]
Hi @bkosborne 

yes, I'm here. I just fixed a problem with tests on jruby-head.
I think we are good to go in a new release.
I think my user does not have this "power", can you do that?
